### ISSUE TITLE
Cannot see the "run" button

### ISSUE THREAD

**Issue by sashakeista** [xAgramon/StitchTool#10]
As the title says, it seems I can't see the "run" button on the very bottom of the software. I can only see watermark and greyscale option. Can you fix it? Thank you

**Comment by Aeonss** [comment]
> As the title says, it seems I can't see the "run" button on the very bottom of the software. I can only see watermark and greyscale option. Can you fix it? Thank you

Can you send an image? Is the window too big? Did you press the drop down button on the sides?

**Comment by sashakeista** [comment]
It is like this 
![image](https://user-images.githubusercontent.com/74736538/161802607-48b2b56d-f2f0-462a-9667-6061f8b4f9b7.png)

**Comment by sashakeista** [comment]
I cannot see the "run" button after greyscale and watermark option based on readme

**Comment by Aeonss** [comment]
You resized the window you so couldn't see it.

**Comment by Aeonss** [comment]
Expand the window downwards

**Comment by sashakeista** [comment]
How do I expand the window downwards?

**Comment by Aeonss** [comment]
Hover of the bottom edge of the window until you see ↕ and pull down

**Comment by sashakeista** [comment]
I already did it, but it's still the same. There is greyscale and watermark, but no "run" button

**Comment by Aeonss** [comment]
Did you pull all the way down? If you're out of room try clicking the ↓ under the red text field or any other one and pull down again. The run button is probably hidden maybe due to your screen size. What size is your resolution? Also send a screenshot of it being "all the way down" if it still doesn't work.

**Comment by sashakeista** [comment]
So, I tried your suggestion "_If you're out of room try clicking the ↓ under the red text field or any other one_" and it's working. 
![image](https://user-images.githubusercontent.com/74736538/161806319-2d66138d-184a-4bc8-b0ec-1718444c9913.png)
